{
	"description": "The python-pillow packages contain a Python image processing library that provides extensive file format support, an efficient internal representation, and powerful image-processing capabilities.\n\nSecurity Fix(es):\n\n* python-pillow: Out-of-bounds read in J2K image reader (CVE-2021-25287)\n\n* python-pillow: Out-of-bounds read in J2K image reader (CVE-2021-25288)\n\n* python-pillow: Negative-offset memcpy in TIFF image reader (CVE-2021-25290)\n\n* python-pillow: Regular expression DoS in PDF format parser (CVE-2021-25292)\n\n* python-pillow: Out-of-bounds read in SGI RLE image reader (CVE-2021-25293)\n\n* python-pillow: Excessive memory allocation in BLP image reader (CVE-2021-27921)\n\n* python-pillow: Excessive memory allocation in ICNS image reader (CVE-2021-27922)\n\n* python-pillow: Excessive memory allocation in ICO image reader (CVE-2021-27923)\n\n* python-pillow: Excessive memory allocation in PSD image reader (CVE-2021-28675)\n\n* python-pillow: Infinite loop in FLI image reader (CVE-2021-28676)\n\n* python-pillow: Excessive CPU use in EPS image reader (CVE-2021-28677)\n\n* python-pillow: Excessive looping in BLP image reader (CVE-2021-28678)\n\n* python-pillow: Buffer overflow in image convert function (CVE-2021-34552)\n\n* python-pillow: Buffer over-read in PCX image reader (CVE-2020-35653)\n\n* python-pillow: Buffer over-read in SGI RLE image reader (CVE-2020-35655)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the AlmaLinux Release Notes linked from the References section.",
	"id": "ALSA-2021:4149",
	"issued_date": 1636446274,
	"modules": [],
	"packages": [
		{
			"arch": "x86_64",
			"checksum": "c9ab9992660c3f6bca80ac9b33fcf2de87e39826817ce1655c7fd4db49a7d56c",
			"checksum_type": "sha256",
			"epoch": "0",
			"filename": "python3-pillow-5.1.1-16.el8.x86_64.rpm",
			"name": "python3-pillow",
			"reboot_suggested": 0,
			"release": "16.el8",
			"src": "python-pillow-5.1.1-16.el8.src.rpm",
			"version": "5.1.1"
		}
	],
	"references": [
		{
			"href": "https://vulners.com/cve/CVE-2020-35653",
			"id": "CVE-2020-35653",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2020-35655",
			"id": "CVE-2020-35655",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-25287",
			"id": "CVE-2021-25287",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-25288",
			"id": "CVE-2021-25288",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-25290",
			"id": "CVE-2021-25290",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-25292",
			"id": "CVE-2021-25292",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-25293",
			"id": "CVE-2021-25293",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-27921",
			"id": "CVE-2021-27921",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-27922",
			"id": "CVE-2021-27922",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-27923",
			"id": "CVE-2021-27923",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-28675",
			"id": "CVE-2021-28675",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-28676",
			"id": "CVE-2021-28676",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-28677",
			"id": "CVE-2021-28677",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-28678",
			"id": "CVE-2021-28678",
			"type": "cve"
		},
		{
			"href": "https://vulners.com/cve/CVE-2021-34552",
			"id": "CVE-2021-34552",
			"type": "cve"
		}
	],
	"severity": "Moderate",
	"title": "Moderate: python-pillow security update",
	"type": "security",
	"updated_date": 1636712456
}
